import com.google.common.base.Objects;
import org.junit.Test;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;

import static com.google.common.truth.Truth.assertThat;

/**
 * This is an integration test.
 *
 * <p>The class Yylex is generated by JFLex from {@code src/main/jflex/simple.flex}.
 *
 * @author Régis Décamps
 */
public class YylexTest {


  /** Tests that the generated {@link Yylex} lexer behaves like expected. */
  @Test
  public void output() throws Exception {
    File inputFile = openFile("src/test/data/test.txt");
    assertThat(inputFile.isFile()).isTrue();

    Yylex yylex = new Yylex(new FileInputStream(inputFile));

    System.out.println(yylex.yylex().getToken());
    System.out.println(yylex.yylex().getToken());

  }

  private static File openFile(String pathName) throws IOException {
    String path = pathName;
    File pwd = new File(".").getCanonicalFile();
    assertThat(pwd.isDirectory()).isTrue();
    if (Objects.equal(pwd.getName(), "__main__")) {
      path = "jflex/examples/simple/" + path;
    }
    File file = new File(path);
    if (!file.isFile()) {
      throw new FileNotFoundException(path);
    }
    return file;
  }
}
